name: Render PDF

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Quarto
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          # Lade die neueste Version von Quarto herunter und speichere sie als "quarto-linux-amd64.deb"
          wget -O quarto-linux-amd64.deb  https://github.com/quarto-dev/quarto-cli/releases/download/v1.6.40/quarto-1.6.40-linux-amd64.deb
          sudo dpkg -i quarto-linux-amd64.deb

      - name: Install LaTeX (TexLive)
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-latex-extra

      - name: Render Quarto document to PDF
        run: quarto render iv_in_python.md --to pdf

      - name: Rename PDF file
        run: mv iv_in_python.pdf iv_in_python_rendered.pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: rendered-pdf
          path: iv_in_python_rendered.pdf
