name: Render PDF

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Quarto
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.6.40/quarto-1.6.40-linux-amd64.deb
          sudo dpkg -i quarto-1.6.40-linux-amd64.deb

      - name: Render Quarto document to PDF
        run: quarto render document.qmd --to pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: rendered-pdf
          path: document.pdf
